#!/bin/bash
# Logo Yaourt-Gui-Manjaro
#
# Customize: http://www.network-science.de/ascii/
#
# example color:
# BLUE="\033[1;34m" 
# RED="\033[1;31m"
# WHITE="\033[1;37m"
# GREEN="\033[1;32m"
# YELLOW="\033[1;33m"
#

start="\033[1;32m"
reset="\033[0m"
colorlogo=`echo $LANG | cut -c1-2`

echo -e "$start                  __  __             _                 $reset"
echo -e "$start                 |  \/  |           (_)                       $reset"
echo -e "$start                 | \  / | __ _ _ __  _  __ _ _ __ ___        $reset"
echo -e "$start                 | |\/| |/ _\` | '_ \| |/ _\` | '__/ _ \     $reset"
echo -e "$start                 | |  | | (_| | | | | | (_| | | | (_) |    $reset"
echo -e "$start                 |_|  |_|\__,_|_| |_| |\__,_|_|  \___/     $reset"
echo -e "$start                                   _/ |                    $reset"
echo -e "$start                                  |__/                     $reset"

## END SCRIPT
